### PR TITLE
Apply pkg-config patch

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
This fixes the build failure in https://github.com/conda-forge/librsvg-feedstock/pull/69

**Comment by pkgw** [comment]
Hmm, it seems like it might be better to fix whichever pkg-config file is adding the `-lm` on Windows, rather than patching it out in the g-i stage? Or is there some reason that's not feasible? I'd be curious to know what upstream has to say.

cf: https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/265 (linked in the patch)

**Comment by tschoonj** [comment]
`m.lib` is already filtered out when the introspected library directly depends on it: https://github.com/GNOME/gobject-introspection/blob/10b1a869da09d260e54b6f28a0d2c0e3015deee4/giscanner/ccompiler.py#L223-L224 and https://github.com/GNOME/gobject-introspection/blob/10b1a869da09d260e54b6f28a0d2c0e3015deee4/giscanner/ccompiler.py#L247-L248

**Review by pkgw — APPROVED** [review]
@tschoonj Ah, that's pretty compelling.

**Comment by ocefpaf** [comment]
> @tschoonj Ah, that's pretty compelling.

@pkgw I have to confess I don't understand the changes but if you are OK I'm also +1. Merge?

**Comment by pkgw** [comment]
@ocefpaf Here's my attempt at a recap: it seems that on Windows, some projects publish pkg-config files that include a `-lm` dependency, but there's no such library on Windows. Now I'm kind of tempted to say that those pkg-config files should be fixed ... but gobject-introspection already has some hacks to filter out these deps when it does its introspection magic. It seems that `librsvg` is triggering a corner case where another filter needs to be added.

**Pull request merged**
