### PR TITLE
recipe/build.sh: fix typo in cross-build script

### PR DESCRIPTION
**Pull request by pkgw**
Typo fix for the cross-build script. See also conda-forge/librsvg-feedstock#77, conda-forge/pango-feedstock#45, conda-forge/gtk3-feedstock#39.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ryanvolz** [comment]
@pkgw I think the blocking broken package was `gettext`, and that has now been fixed. You can probably kick the `pango` and `librsvg` builds now.

**Comment by pkgw** [comment]
@ryanvolz Looks like the Python 3.6 build still failed. Do you happen to know if it's just that the 3.6 builds aren't getting updated anymore? `gettext` isn't Python-specific though so it wouldn't be that package, I think.

**Comment by ryanvolz** [comment]
It looks like the only `python=3.6` that was built with `libffi=3.4` for linux-ppc64le was marked as broken (by virtue of unlucky timing, the only Python version affected that doesn't have a more recent build) and hasn't been rebuilt. Perhaps an oversight, because @isuruf has already closed all the Python rebuild PRs?

**Comment by isuruf** [comment]
Fixed now

**Comment by ryanvolz** [comment]
Thanks Isuru!

**Comment by pkgw** [comment]
Great, thanks!

**Pull request merged**
