### PR TITLE
Update actions

### PR DESCRIPTION
**Pull request by reinaldojohnson1**

### CODE REVIEW

**Comment by tschoonj** [comment]
This looks more than suspicious to me

**Comment by tschoonj** [comment]
I have reported this user, and expect that he will be kicked off from Github soon. I have no doubt that he will try this again with a different account soon though...

**Comment by pkgw** [comment]
Sigh. I reported this PR as well, just in case that helps. I hope this doesn't become a routine thing.

**Comment by xhochy** [comment]
Sadly a common pattern the last weeks 😕

**Pull request closed without merging**
