### PR TITLE
Split into multiple outputs

### LINKED ISSUE #32: Split gobject-introspection into multiple outputs
The idea springs from [this comment](https://github.com/conda-forge/gdk-pixbuf-feedstock/pull/24#issuecomment-709498213), which references [this nice overview](https://gi.readthedocs.io/en/latest/). It's also motivated by the recent shift by `gtk3` and `gdk-pixbuf` to move `gobject-introspection` from a host dependency to a build dependency since they use `g-ir-scanner` as a build tool. It would be nice to do similar with other packages, but `pygobject` for example actually needs parts of the current `gobject-introspection` (`libgirepository`) as a run dependency. I'm making this issue to foster discussion and act as a reminder.

You can see how Debian splits `gobject-introspection` [here](https://packages.debian.org/source/sid/gobject-introspection). At a minimum, I'd say it would be nice to have a separate `libgirepository` package. I'm less clear about the utility of the further splits that Debian has (aside from the typical base and "-dev" splits which is not typically something that conda-forge does).

### PR DESCRIPTION
**Pull request by ryanvolz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #32.

Here's an attempt at splitting `gobject-introspection` into multiple outputs. It preserves `gobject-introspection` as the package to build against that includes everything, and it additionally creates outputs for `libgirepository`, `g-ir-build-tools`, and `g-ir-host-tools`.

I opted to make separate packages for the Python tools (build) and compiled tools (host) since other folks dealing with cross-compilation issues have seemed to find it helpful (e.g. [yocto](https://github.com/Guacamayo/meta-gir) and [NixOS](https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/224/diffs)). The idea, if I understand it correctly, is that one would run `g-ir-scanner` on the build machine and specify emulation wrappers for running both the host version of `g-ir-compiler` and the host executables that `g-ir-scanner` creates. I don't know yet if it will actually make anything easier for conda-forge, so we can fold those back in to `gobject-introspection` if people think it is unnecessary.

Is there anything about where I've drawn the boundary between packages that looks incorrect? Is there anything that would want to build against `libgirepository` and not the entirety of `gobject-introspection` and so would need the development files (e.g. headers)?

Are any further splits desirable (e.g. separating the gir/typelibs)?

### CODE REVIEW

**Comment by pkgw** [comment]
Thanks for taking this project on! Is this PR ready for review?

**Comment by ryanvolz** [comment]
Yup, ready for review.

**Comment by pkgw** [comment]
OK, I've taken a look over the changes here. I haven't done any detailed investigations of trying to build any downstream packages or anything.

It pretty much all looks good to me. The only suggestion I have is that I think that the typelibs (`$prefix/share/gir-1.0`) shouldn't go in the high-level `gobject-introspection` package. As I understand it, programs that *use* the g-i framework are going to link to libgirepository, which will then in turn access and load typelib files to provide introspection information at runtime. So I think I want to say that the typelibs should go in the `libgirepository` package — they're runtime resources tied to that library, not development files.

The GIRs could potentially go into a separate data package, and there might be a possible gain there if that package could be `noarch`, as implied by the placement of the files in `$prefix/share`. On the one hand, I'm pretty sure that the typelib files contain some information about the binary layouts of various C structures, so I have trouble seeing how those files could actually be `noarch`. On the other hand, the folks who work on g-i are definitely aware of these things, and `$prefix/share` is where they put them.

**Comment by ryanvolz** [comment]
Based on what I've read (I have no direct experience), I think the XML GIR files could indeed be noarch. The only real question I'd have is if they are actually ever needed at runtime by, e.g., `pygobject`, because it was my impression that such applications only use the binary typelibs (which *are* part of `libgirepository`). I thought the XML GIRs are only relevant for development/compilation, so that's why I shoved them into `gobject-introspection`. Maybe @tschoonj would know from experience what we need to do here? It's easy enough to make the XML GIRs into a noarch package and have them be a dependency of either `libgirepository` or `gobject-introspection` (depending on which is correct). But I don't know if it's even worth the bookkeeping if they could just be added to those outputs directly.

**Comment by pkgw** [comment]
Riiiight it's the typelib files, not the GIR files. I think you're correct that the GIR XMLs are not used at runtime, so I think that what you've got in the current PR is correct.

**Comment by tschoonj** [comment]
I will try and review this PR tomorrow or this weekend. Hope that's ok.

**Comment by tschoonj** [comment]
Had a quick look and mostly looks good.

However:

* I am not sure that dividing the executables  over `g-ir-build-tools` and `g-ir-host-tools` is going to get us much honestly. But as you said, if it turns out to be like that, we can always move them back into the main package.
* The gir files are not used at runtime by pygobject. But they do need to be installed as they are used when generating new gir/typelib files that depend on them. This is why you need to define `export XDG_DATA_DIRS=${XDG_DATA_DIRS}:$PREFIX/share` in some cases like gtk3.
* The gir files should not end up in a noarch package: they contain paths to dlls, so's and dylibs depending on the platform they were built for. Also the symbols that they contain are not necessarily the same across all platforms. GLib adds Windows exclusive API for example.

**Comment by ryanvolz** [comment]
>     * The gir files are not used at runtime by pygobject. But they do need to be installed as they are used when generating new gir/typelib files that depend on them. This is why you need to define `export XDG_DATA_DIRS=${XDG_DATA_DIRS}:$PREFIX/share` in some cases like gtk3.

Isn't this the case where one would use `gobject-introspection` as a build dependency anyway, and so the gir files would be there with the current structure? If I'm misunderstanding, I'm happy to move them to `libgirpository`. I guess the best question is this: is there any way that some package will need the gir files for its build but not also need the other things that come with `gobject-introspection`?

**Comment by tschoonj** [comment]
I think that the `gir` files should go in the same package that has the headers, which I understand is `gobject-introspection`?

**Comment by ryanvolz** [comment]
Ok, that's a simple rule, and yes, that's where they currently are.

**Review by pkgw — APPROVED** [review]
Based on the discussion above ... I think this is OK to merge, no?

**Comment by ryanvolz** [comment]
Yes, I think all questions have been answered. It's ready to go as I see it.

**Comment by pkgw** [comment]
I'll plan to merge this tomorrow unless @tschoonj has any other comments.

**Comment by tschoonj** [comment]
I am fine with the proposed changes

**Pull request merged**
