### PR TITLE
Bump to 1.64.1

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@conda-forge-admin, please restart ci

**Comment by tschoonj** [comment]
@ocefpaf @pkgw @scopatz This one is ready for review.

I have taken the liberty of adding myself as maintainer, I hope that's ok.

**Comment by tschoonj** [comment]
@pkgw nobody seems to have any other comments, so feel free to merge it in.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
