### PR TITLE
Remove conda inspect from tests

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
Thanks @erykoff, can you please explain why this is needed.

**Comment by isuruf** [comment]
This check is deprecated in conda-build AFAIK and doesn't work in platforms like `osx-arm64`. This functionality is replaced in conda-build by lief/pyldd and is now done automatically even without the `conda inspect` calls.

**Comment by beckermr** [comment]
@scopatz We have a bot minimigrator running to remove these lines from all recipes now.

**Comment by hmaarrfk** [comment]
this is good to go then right?

**Comment by beckermr** [comment]
Yup

**Pull request merged**
